# Support Open Source Development
# Help maintain and improve these tools

github: erdalgunes
ko_fi: erdalgunes
liberapay: erdalgunes
open_collective: erdalgunes
custom: ["https://buymeacoffee.com/erdalgunes", "https://www.paypal.me/erdalgunes"]
